name: CI/CD - Build and Deploy to EC2

on:
  push:
    branches:
      - master  # hoáº·c branch báº¡n muá»‘n deploy

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: âœ… Checkout source code
        uses: actions/checkout@v4

      - name: ğŸŸ¢ Setup Node.js (latest LTS)
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'  # hoáº·c cá»¥ thá»ƒ: '20'
          cache: yarn

      - name: ğŸ“¦ Install dependencies
        run: yarn install --frozen-lockfile

      - name: ğŸ—ï¸ Build project
        run: yarn build

      - name: ğŸ“¤ Deploy to EC2 via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 54.151.191.185
          username: deploy
          password: 1l8F0zfPq64mB1yCBVSckQMbW
          port: 22
          source: "out/**"   # tÃ¹y theo thÆ° má»¥c build cá»§a báº¡n
          target: /var/www/blablo/pc   # thÆ° má»¥c Ä‘Ã­ch trÃªn EC2
